### ISSUE TITLE
DF User Logger: Change chime and phrases from settings

### ISSUE THREAD

**Issue by smoothingplane** [flamewave000/dragonflagon-fvtt#105]
It would be easier to change the chime sound and to be able to change the passphrases (and also their number if you want), directly from the module settings (without them being lost after an update).

**Comment by flamewave000** [comment]
This has been on my todo list for quite a while. I just haven't had the time to work on it yet.

**Comment by Doresain** [comment]
Hey man, thanks for the great mods!

So I was migrating to 0.8.7 on a new world and enabling a lot of modules one by one, and this chime from a source I couldn't find was driving me crazy, haha. 

I am an *exceptionally* novice developer, but when I figured out what was doing it the required changes to add a client-side sound enable/disable toggle and a world-scoped setting for which file to play seemed simple enough - I thought I might be able to get it working and then just give you a PR to make it easy. 

Turns out you're doing something too complex for me to navigate between code and release, and I couldn't figure out how to easily test my changes in Foundry, RIP. 

So instead I'm just coming here with my hands out to beg for a toggle on the sound feature. :) 

Thanks!

**Comment by flamewave000** [comment]
@Doresain  Yeah, I highly automated the build system so that I can rapidly develop and debug my mods all from within VScode. It's a bit complex to get setup and going for a beginner. I'll see if I can get around to this one sometime this week. I got bogged down in the 08x migration and haven't done much more than bug fixes the past week or so.

**Comment by flamewave000** [comment]
Alright, I finally got around to working on this. I had a hell of a time getting the CSS to behave properly for some unknown reason lol. but it is working quite well so I'll leave it at that 👍🏽 
![image](https://user-images.githubusercontent.com/3588046/123562145-c968c280-d77a-11eb-81a9-e033f725c05c.png)
![image](https://user-images.githubusercontent.com/3588046/123562154-d4bbee00-d77a-11eb-92db-f38e27b4907f.png)
