### ISSUE TITLE
DF Manual Dice: Reworked Version?

### ISSUE THREAD

**Issue by Smart-Helper** [flamewave000/dragonflagon-fvtt#111]
Hello :-)

First of all - i LOVE the idea behind that mod. I'd love to use it because 2 of my 4 players prefer to roll with real dice.
I on the other hand, as the DM, want to automate as much work as possible...and Number crunching is the not fun part of DnD.

So i found the "Issue-Post" where the dice prompt will show up twice due to Midi QoL and the automated system in there.

So i want to ask if you plan on reworking the module alltogether to achieve multiple things and possible enhancements:

1) Prompt with the ingame UI to a) make it look better and more integrated and b) make it work in the desktop app too
2) Make it work with Midi QoL to make it usable by us lazy DMs who dont like number crunching
3) Make it so you enter the SUM of all your dice rolled...tbh it is absolutely terrible to enter every single dice roll of a Fireball on level 5....like absolutely terrible :-/
4) Make it so you can enable the manual rolling for only selected players...As i said 2 of my 4 players roll manually so i'd love for the other 2 to not be bothered by any pop-up / prompt every time they roll something
5) In conjunction with 1) it is unbearable to get the notification that you can use this only in your browser when you try to roll something as the DM in the desktop application...As the DM i wont use the browser ever. I will stick to the desktop application.

So to summarize this;
The Idea is fantastic and i believe that there is very much need for this module. The execution however is unusable for many of us. Be it that there are some people who do automated rolling or automated appliage of damage or people who dont want to use the browser because its unefficient and interrupts your workflow with certain unwanted interactions with hotkeys and key-combos. Also the constant pop-ups for players who dont want to roll manually is annoying but that would be acceptable if everything else would work better.

I hope you dont take this too negative. I am no programmer by myself sadly but  i have a good enough grasp on this to believe that my proposed enhancements should be doable.
I really like your work and if the things i mentioned above would be featured in future updates i will be the happiest foundry DM and my wife and my other player would love you for that :-D

**Comment by flamewave000** [comment]
So it is currently not possible to do these improvements. Except for 4, if you turn off "Force Manual Roll", each individual player can choose to have the manual rolls enabled or not.

Currently rolling in foundry has to be done immediately. There is no way for the system to "wait" for the roller to display a window to ask the user for input. Right now I'm using the web standard Prompt which literally pauses the entire web page. This is the only way it can be done until 0.8.x where Atropos has finally been able to update the rolling system to use "Asynchronous Rolls". As for the issue of it not working in the app, that is due to Electron (the container foundry uses) not supporting the web standard Prompt. It blows my mind that they refuse to support it.

Anyways, you will have to wait until the release of 08x and my then subsequent update to Manual Rolls before you can potentially see these improvements.

**Comment by Smart-Helper** [comment]
Thank you for you the answer.

I dont have "Force Manual Roll" activated but it still pops up whenever someone wants to roll.

Well then i wait and hope to see your awesome addon in 0.8.x :-)

**Comment by flamewave000** [comment]
Ech player that doesn't want to do manual rolling needs to open their configuration settings and Uncheck the "Use Manual Rolls" option.
