### ISSUE TITLE
DF User Logger: Conflict with automated-jb2a-animations

### ISSUE THREAD

**Issue by Merudo** [flamewave000/dragonflagon-fvtt#114]
** Conflicting Module(s)**
- automated-jb2a-animations

**Describe the conflict**
When a user logs in and automated-jb2a-animations is enabled, an error is thrown into the console

**Expected behavior**
No error in the console from a user logging in.

**Screenshots**
![image](https://user-images.githubusercontent.com/7371085/117102879-d353e380-ad3e-11eb-82be-5326e1ebbc30.png)

**Additional context (Optional)**
An error report to automated animation https://github.com/otigon/automated-jb2a-animations/issues/46 has been filled, but @otigon claims the bug is entirely due to DF User Logger.

**Comment by flamewave000** [comment]
Not to step on any toes, but the exception is being thrown in their module, not User Logger. All my mod is doing is calling ʼcreateMessage()ʼ just like everything else does. Absolutely nothing special. They're literally simple messages being posted to the Chat. Per the mod's own description:
> Automated Animations reads the data passed through Chat Cards
This tells me they are parsing all the messages and "thinking" a message from User Logger is somehow important and needs to be animated. This is likely due to not handling special characters, or doing pattern matching that is too broad. Literally nothing I can do, the ball is entirely in their court to improve their message processing code.
