### ISSUE TITLE
DF Curvy Walls: Add support for Button Overflow ~Option to put Controls in main Walls list~

### ISSUE THREAD

**Issue by Tristan-Goucher** [flamewave000/dragonflagon-fvtt#117]
**Is your feature request related to a problem? Please describe.**
I think a previous update made the Curvy Wall controls into its own element in the UI. I recently found and started using the module [Button Overflow](https://github.com/ardittristan/VTTButtonOverflow), which allows for buttons to roll over into another column. Unfortunately as seen in the picture below, the DF Curvy Wall controls aren't included in the main element and will be obscured instead.

![image](https://user-images.githubusercontent.com/72034470/118459598-c1643000-b6b0-11eb-8a90-374a5a0f9ddc.png)

**Describe the solution you'd like**
Since I don't want to ask for a reversion to a possibly-non-existent behavior, I'd like to request a GM-only option in the module settings to decide whether the Curvy Walls controls are in their own element or tacked onto the existing wall controls. Then I could just toggle that on and be good to go.

**Comment by flamewave000** [comment]
So I don't plan to revert back as the new UI is a complete rebuild and is actually running much better than when I had to try and get the condos into the main control set.

Instead I can maybe try grabbing the Controls element and adjusting my X position if the controls element has expanded. As such, this ticket is a conflict issue since Curvy Walls works as expected in core Foundry.

**Comment by flamewave000** [comment]
Finally got around to getting this fixed up 👍🏽 
![image](https://user-images.githubusercontent.com/3588046/123566725-62ed9f80-d78e-11eb-8f24-c5dbdfd879e5.png)
