### ISSUE TITLE
DF Chat Enhancements: Customize Path for Chat Archives

### ISSUE THREAD

**Issue by patrickburk1988** [flamewave000/dragonflagon-fvtt#132]
**Is your feature request related to a problem? Please describe.**
Creating a chat archive in Forge creates a `worlds/[world-slug]/chat-archive` directory in which the archive is stored. Some users may have their Assets Library arranged differently. I personally would prefer to store my chat archives in `[World Name]/Chats`.

**Describe the solution you'd like**
A global setting with a text field to manually choose a path where chat archives are stored (and where they are retrieved from when using the "DF Chat Archive Manager" dialog in the settings sidebar.

**Comment by TheLaslo** [comment]
I think related to this is this error when a Player logs in.  The players do not have access to the /log command, I'm assuming due to a failure in building up the logger.
<html>
<body>
<div role="treeitem" aria-expanded="true" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span class="console-message-text" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: var(--error-text-color)  !important;">Uncaught (in promise) <span class="object-value-error source-code" style="box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--source-code-font-family); white-space: pre-wrap; font-size: var(--source-code-font-size)  !important; line-height: 1.2;"><span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">Error: Could not access the archive folder: worlds/savage-sand-new/chat-archive
<span style="box-sizing: border-box; min-width: 0px; min-height: 0px;">    at <span class="devtools-link" role="link" tabindex="-1" style="box-sizing: border-box; min-width: 0px; min-height: 0px; color: rgb(84, 84, 84); text-decoration: underline; cursor: pointer; word-break: break-all;">df-chat-enhance.js:3</span></span></span></span></span></span></div><div class="" role="group" style="box-sizing: border-box; min-width: 0px; min-height: 0px; flex: 0 0 auto; color: rgb(34, 34, 34); font-family: consolas, &quot;lucida console&quot;, &quot;courier new&quot;, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(236, 241, 248); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="monospace" style="display: inline-block; --monospace-font-size: 12px; --monospace-font-family: consolas, lucida console, courier new, monospace; --source-code-font-size: 12px; --source-code-font-family: consolas, lucida console, courier new, monospace; box-sizing: border-box; min-width: 0px; min-height: 0px; font-family: var(--monospace-font-family); font-size: var(--monospace-font-size)  !important;">

  | (anonymous) | @ | df-chat-enhance.js:3
-- | -- | -- | --
  | Promise.catch (async) |   |  
  | createArchiveFolderIfMissing | @ | df-chat-enhance.js:3
  | registerSettings | @ | df-chat-enhance.js:3
  | init | @ | df-chat-enhance.js:13
  | (anonymous) | @ | df-chat-enhance.js:31
  | _call | @ | VM6213:4
  | callAll | @ | foundry.js:153
  | initialize | @ | foundry.js:4190
  | 🎁call_wrapped | @ | libWrapper-wrapper.js:465
  | 🎁libWrapperInit | @ | libWrapper-api.js:599
  | 🎁Game.prototype.initialize#0 | @ | libWrapper-wrapper.js:160
  | window.addEventListener.once | @ | foundry.js:53180
  | async function (async) |   |  
  | window.addEventListener.once | @ | foundry.js:53179

</span></div>
</body>
</html>

**Comment by happy-cujo** [comment]
There is a mistake within the logic in: https://github.com/flamewave000/dragonflagon-fvtt/blob/af5f007b7cbc51eaa88b81fc071266ff014a04fb/df-chat-enhance/src/archive/DFChatArchive.ts#L62

The file creation should be in catch callback, because if folder is missing the `Directory worlds/${game.world.id}/chat-archive does not exist or is not accessible in this storage location` error is thrown.

Other approach would be to simply execute FilePicker.createDirectory.

@flamewave000 The issue with not creating the folder is pretty serious, because you can loose all of the chat data if you try to use "create archive and remove messages" option - and that option is selected by default on the archive creation form. If folder is not correctly initialized the archive creation will fail, but it will still remove all of the messages (and that action cannot be reverted which results in loosing whole defined history).

As a workaround for current state I've used below code that can be run from a console or via script macro:
```js
FilePicker.createDirectory('data', game.settings.get('df-chat-enhance', 'archiveFolder'))
    .then(() => console.log('success'))
    .catch(err => console.log(err));
```
