### ISSUE TITLE
DF Manual Rolls: Some formulas creates dialogs with empty roll terms

### ISSUE THREAD

**Issue by plutoneld** [flamewave000/dragonflagon-fvtt#134]
**Module**
DF Manual Rolls 2.0.0

**Describe the issue**
This is a bit fuzzy... I had a Breath Weapon with an "odd" formula, containing for instance `ceil`. It ended up producing dialogs according to the linked screenshot.

Unfortunately, I cleared my chat windowed, deleted the Breath Weapon feature, and imported the Breath Weapon from SRD - and not thinking to retain the original formula. You can however replicate the issue with `/r ceil(5/3)d6`, which produces the final roll term (2d6) but also an empty dialog.

**Screenshots (Optional)**
https://cdn.discordapp.com/attachments/716491110691635241/853883423244025856/unknown.png

**Comment by flamewave000** [comment]
I got this one figured out. So the one window is actually valid for accepting rolls. The others were caused by parts of the roll not containing any "Dice Rolls". This likely would have been a problem with even a roll like `/r 42`. I've got it fixed to ignore displaying dialogs for any rolls that don't contain "Dice" terms.
