### ISSUE TITLE
DF User Logger: Italian Localization

### ISSUE THREAD

**Issue by smoothingplane** [flamewave000/dragonflagon-fvtt#279]
Hi, I translated your module, I put 0 to 63 entry messages, and 0 to 13 exit messages. I'm sending the file.
[it.zip](https://github.com/flamewave000/dragonflagon-fvtt/files/7807106/it.zip)

**Comment by flamewave000** [comment]
Thank you very much for the translations. I do have some notes though. Since this module can be used by underage children, I must keep a [**PEGI 7**](https://pegi.info/index.php/what-do-the-labels-mean) rating. This means no sexual innuendo, drugs/alcohol, and bad language. As such, I found 12 messages that appear to me as potentially violating those rules. I have attached a modified version of your submission that has those lines flagged.

Aside from that, there are some missing strings that I've included as English (Please feel free to translate or ignore those), and I have formatted the file to fit with how the latest translations are structured. I've also spotted 2 duplicate entries which I've flagged for you in case you would like to replace them with something else.

Again, I'm very sorry for the hassle and I hope you understand. If you feel I am misunderstanding a line you provided, please feel free to inform me and we can certainly discuss. I do not speak Italian, so I'm mainly relying on Google Translator for verifying these.

[it_revised.zip](https://github.com/flamewave000/dragonflagon-fvtt/files/7810518/it_revised.zip)

**Comment by smoothingplane** [comment]
I apologize for the most abusive messages, I had not thought about the children 😆.
I eliminated the "dangerous" messages, the ones I left are not considered one of the categories you mentioned in Italian:

"Dannato  {{username}}, entrando ha rovinato la festa" even if "dannato" can be translated as damned, in Italian it is not swearing

"{{username}}! {{username}}! È arrivato {{username}}! Visto? Non gliene frega niente a nessuno." it is a quote from jurassic park, it does not contain swearing, at most it could be considered a mockery

"{{username}}, buonasera e ben ritrovato, un saluto affettuoso a lei. L'ultima volta ci siamo divertiti, direi più lei che me"  is a quote from a famous teleseller of carpets and paintings, let's say that it is a trashy character from Italian TV (Alessandro Orlando), the phrase refers to the fact that the last time buyers bought stuff at low prices (actually it's not true, that's why it's trash) and so they had fun.

"Ciao {{username}}, sei un maschio o una femmina?" is the famous phrase of the first pokemon, where the prof. oak asks the player if he is male or female (I can understand why it can be considered in one of the categories)

"{{username}} dammi un Benny per provare a uscire illeso." and "{{username}} è morta e io ho avuto un Benny gratis." here I did not understand the category, perhaps for the word "benny"? is meant the benny of Savage Worlds, the game mechanics.

anyway thank you for the review, and if the sentences are always considered wrong, don't worry about deleting them.

**Comment by smoothingplane** [comment]
[it_revised again.zip](https://github.com/flamewave000/dragonflagon-fvtt/files/7810824/it_revised.again.zip)

**Comment by smoothingplane** [comment]
[it_revised again .zip](https://github.com/flamewave000/dragonflagon-fvtt/files/7810897/it_revised.again.zip)

**Comment by flamewave000** [comment]
Thank you for the clarity! Again, I'm only armed with google translate to check things, which as everyone knows is not the best. If it is not a "swear" in Italian, I'm fine with it 👍🏽 I appreciate you helping with this. Also, if you want to add extra messages to your own server, you can do so in the Module Settings.

My confusion over "Benny" is that it's technically a known name for a type of narcotics. But if in this case it is being used as a person's name, it is totally fine. Honestly, I have no idea how "benny" started getting used in that way though lol.

**Comment by smoothingplane** [comment]
🤣 🤣 🤣  Okay, I didn't know benny was a way of calling narcotics.
This could be a problem for Savage Worlds: https://wiki.roll20.net/Savage_Worlds#:~:text=In%20Savage%20Worlds%2C%20Bennies%20are,Joker%20is%20drawn%20during%20initiative.&text=In%20order%20to%20easily%20track%20Bennies%2C%20create%20a%20custom%20card%20deck.

**Comment by flamewave000** [comment]
haha it's probably fine. It's a little bit more of an out-dated term for Amphetamine tablets that are used ADHD patients. But Benny is also technically a name, and I was only concerned based on how Google Translate was translating the overall sentence.

**Comment by flamewave000** [comment]
Released in [DF User Logger v1.6.7](https://github.com/flamewave000/dragonflagon-fvtt/releases/tag/df-logger_1.6.7)
