### ISSUE TITLE
DF Template Enhancement: rectangle templates are no longer working with Automated Animation

### ISSUE THREAD

**Issue by DarKDinDoN** [flamewave000/dragonflagon-fvtt#333]
**Module**
Related to: https://github.com/otigon/automated-jb2a-animations/issues/369

Automated Animation is not able to play an animation through Sequencer on a square template with this new feature: https://github.com/flamewave000/dragonflagon-fvtt/blob/master/df-templates/CHANGELOG.md#release-110-2022-03-08

**Comment by Mavendorn** [comment]
Was just testing this out on my own game and found A-A effects will only play with the "fix square rotate" feature unchecked otherwise you will get this console error from A-A's sequencer 
`lib.js:403 Uncaught (in promise) Error: Sequencer | Module: Automated Animations | Effect | play - Could not determine where to play the effect!
[Detected 1 package: sequencer]
    at Module.custom_error (lib.js:403:12)
    at Proxy._customError (sequencer.js:182:20)
    at Proxy._expressWarnings (effect.js:846:33)
    at Proxy.run (effect.js:855:14)
    at section.js:169:30`

**Comment by flamewave000** [comment]
This is understandable. Unfortunately it is not something I can fix. I'm replacing the rectangle shape with a Polygon, so AA is likely not able to handle that.

I'll need to reach out to the AA dev to see if something can be done on their side to handle the new square rotation

**Comment by DarKDinDoN** [comment]
I'm ok with disabling thé feature. Rotating a square is hardly use anyway.

**Comment by flamewave000** [comment]
Yeah, there aren't very many spells that use square templates. But for that one time you do, hopefully we can still get you a pretty animations 👍🏼
