### ISSUE TITLE
DF Manual Rolls: Enhancement to allow more customized options

### ISSUE THREAD

**Issue by TheSelfEvident** [flamewave000/dragonflagon-fvtt#340]
My party plays as a mixed group of online and in person players. I am switching over from Roll20 mid-campaign. I am going to use you **Manual Rolls** module. However, I would like a way to choose (as the DM) which players will have manual rolls who are playing in person and automatic rolls for those online.

**Describe the solution you'd like**
I have a couple ideas on how this could be accomplished:

1. A setting within the Module Settings that allows for which players are selected as Manual Rollers.
2. A setting within the Token Sheet that can be checked.
3. Rather than a setting: A button added to the pop-up dialogue box that gives the option for an automatic roll when the Manual Roll toggle is on.

Any of these options would allow for the DM to not have to manually toggle the feature on and off between each player's turn or their own turn when they are rolling for the monsters.

**Describe alternatives you've considered (Optional)**
A detailed way to make a macro for the toggling on and off the feature for tokens or a keystroke.

**Comment by flamewave000** [comment]
For option 3, this is already a feature. You simply close the dialog, or click submit without filling in the fields.

**On Close:** All rolls will be randomly generated.
**On Submit:** Any empty field will be given a randomly generated value.

But I will be implementing the per-player solution so that each individual player can be given their own setting for Off/Toggle/Always.

**Comment by flamewave000** [comment]
![image](https://user-images.githubusercontent.com/3588046/162642039-b4790a2b-90ae-4b98-bc2b-615012d51a30.png)

This is what I have now
