### ISSUE TITLE
DF Chat Enhancement: Settings button needs a section, merges with CUB

### ISSUE THREAD

**Issue by apoapostolov** [flamewave000/dragonflagon-fvtt#43]
Without its own section in Settings sidebar tab, the Manage Chat Archive button will merge with CUB's section

![image](https://user-images.githubusercontent.com/4083812/107488776-7fe35680-6b90-11eb-9c8d-1a4bfc25fee1.png)

**Comment by flamewave000** [comment]
This appears to be a race-condition issue. CUB is appending their buttons to the Game Settings either before the Chat Archive gets to or is keying their insertion explicitly to the "Return to Setup" button. I'll have to look into their code to see how they insert their settings so that I can account for it.

**Comment by flamewave000** [comment]
I've opened a PR with CUB for adjusting how it adds its buttons https://github.com/death-save/combat-utility-belt/pull/479 
Currently they are targeting the "Return to Setup" button, but should just be appending to the section.

I'll update my injection to also include a header, that way it won't matter which order they are appended to the Game Settings section.
