### ISSUE TITLE
DF Manual Rolls: Damage rolls not working in PF2e system

### ISSUE THREAD

**Issue by dogstarrb** [flamewave000/dragonflagon-fvtt#443]
**Module**
Manual Rolls v2.4.0

**Describe the issue**
When rolling damage rolls in PF2e v4.6.x (post IWR release)

**To Reproduce**
1. Roll an attack from a weapon or spell (works as it should)
2. Click on 'Damage' in spell/attack card
3. Damage is rolled by system dice, rather than prompting for manual input

**Expected behavior**
Prompt window to input manual dice results should appear before printing damage totals.

**Comment by dogstarrb** [comment]
Update to Reproduction steps: **Sometimes** spell card damage prompts correctly; can confirm Scorching Ray single action prompts, Ray of Frost damage does not, Heal 2-action on Living does not

**Comment by flamewave000** [comment]
Unfortunately PF2 still uses this deprecated synchronous rolls. To deal with this you will need to enable Legacy mode in the module settings.

**Comment by stwlam** [comment]
> Unfortunately PF2 still uses this deprecated synchronous rolls. To deal with this you will need to enable Legacy mode in the module settings.

Friendly FYI: this isn't true and hasn't been for about a year now. Though from looking at the module's current implementation, I suspect support won't be extended unless Foundry itself switches to a similar implementation.

**Comment by flamewave000** [comment]
@stwlam based on the issues that this user (#453) has reported, PF2e is indeed still using synchronous rolls for their "critical damage rolls" and some "spell damage rolls".

**Comment by stwlam** [comment]
@this-gavagai Doesn't a `Die` by its lonesome also invariably hit an `_evaluateSync` method?

**Comment by this-gavagai** [comment]
> Doesn't a `Die` by its lonesome also invariably hit an `_evaluateSync` method?
Not here in RollTerm, at least not that I'm seeing. As to why, I believe you've hit the nail on the head below.

> All pf2e system rolls are async without exception. I believe the issue with the module is that it expects all `dice` to be represented in a `Roll`'s top-level `terms` with the lone exception of `PoolTerm`s. Core `Roll`s incidentally meet this expectation, but pf2e system `DamageRoll`s contain `PoolTerms` that may _also_ have constituent `Roll`s with `dice` not among their top-level `terms`.

I think this is right. Specifically, every time the wrapped `DiceTerm.prototype._evaluateSync` method is getting called, it seems the consequence of L91 here:
https://github.com/flamewave000/dragonflagon-fvtt/blob/9a307430fdb7b0d9f497f1d9d72ec941b671b237/df-manual-rolls/src/ManualRolls.ts#L91-L97

Notably, when evaluating `1d6 + 1`, the property `this.rollPrompt` is undefined. When evaulating `1d6`, however, it is defined properly. I think that might be because the check here:
https://github.com/flamewave000/dragonflagon-fvtt/blob/9a307430fdb7b0d9f497f1d9d72ec941b671b237/df-manual-rolls/src/ManualRolls.ts#L69-72
...is looking for DiceTerms and not larger groupings.

**Comment by George1044** [comment]
I figured out a way to fix this using a recursive method to search for ```DiceTerm```s inside the terms instead of relying on the top-level term being a ```DiceTerm```. 
However, I don't have a Linux device on hand to build the project etc. so I was testing directly on the Foundry data module. 
This is what the function looks like:
```
static setRollPromptRecursively(obj, rollPrompt) {   
          if (obj instanceof DiceTerm) {
            // If the object is a DiceTerm, set the rollPrompt
            obj.rollPrompt = rollPrompt;
          } else if (typeof obj === 'object') {
            // If the object is an object, recursively check its properties
            for (const key in obj) {
              if (obj.hasOwnProperty(key)) {
                ManualRolls.setRollPromptRecursively(obj[key], rollPrompt);
              }
            }
          }
        }
```
You would then replace the following code:
```
 for (const of this.terms) { 
 	if (!(term instanceof DiceTerm)) continue; 
 	(<any>term).rollPrompt = rollPrompt; 
 } 
```
by this:
```
for (const term of this.terms) {
            ManualRolls.setRollPromptRecursively(term, rollPrompt);
            }
```

This will make the module work for damage rolls in my experience, so if someone can do a pull request to fix this, feel free.
