### ISSUE TITLE
DF Chat Enhancement: using ingame time

### ISSUE THREAD

**Issue by haukefrahmann** [flamewave000/dragonflagon-fvtt#66]
Would it be possible instead of using the "actual time" a timestamp from "about time" or the corresponding "calender/wheater" module?

**Comment by haukefrahmann** [comment]
if it is nothing you want >> you can "push" me in the right direction and I will fork it and get my own version

**Comment by flamewave000** [comment]
The About Time module does not update the chat log with Game Timestamps. I would need to build that feature into the Chat Log as there's no way to know what "time" it was when a chat message was first posted. I can look into it and see. I will not add the About Time module as a dependency though as that would be too restrictive for the general public, instead I can just check at runtime to see if it is installed.

**Comment by haukefrahmann** [comment]
I think there is a misunderstanding (or I misunderstand how about time works...):

I just do not want the actual time stamp at all when I log something 
but I want the "current timestamp from about time or from calender/wheater"

in calender/wheater you can start/stop the time, so there is always a "current game time" >> that is what I want in the log

**Comment by tposney** [comment]
You do not need the about-time/calendar weather timestamp. game.time.worldTime will return the foundry "time" in seconds since epoch, how you deal with that number is up to you. about-time supports converting that to a game time string, but even if the module is not installed you can use that value as a valid number of seconds since 0 time number.

**Comment by flamewave000** [comment]
This seems like a little bit too large for my current next release. I will have to include it in the next one along with #60

**Comment by Shuggaloaf** [comment]
Hi FW, just came here to make a suggestion to add this feature. I see someone beat me to it. 
To me, I wouldn't want to get rid of the normal time, but just add the game time as an additional stamp to each message. I understand there would be a bit more clutter in messages, but I think it's useful to keep both (maybe give GMs a toggle switch for it?).  

To add on a little on tposney's suggestion of just using `game.time.worldTime`, it would return seconds as they mentioned, but I have an easy, if clunky, way to get it to work: just add a few fields in DFCE settings that the GM _must_ fill out when turning on "game world time". Hours per day, days per year, etc.. I have a formula that already does something like this but don't want to clutter up the thread, just let me know if you're interested. Otherwise, just please accept my +1 for adding this feature.

**Comment by flamewave000** [comment]
@Shuggaloaf the main issue with this is that my module is System-Agnostic, and Calendars are much more complex than a simple seconds/minutes/hours/days. The Harptos calendar for D&D has names for every month, as well as special holidays that do not reside within a month. It's a level of complexity that I'd much rather not deal with.

Alternatively, if I can obtain the date string generated by some kind of calendar, that would be much more preferred. I'll have to look into SimpleCalendar and see if unsoluble's API can give me a good solution.

**Comment by Shuggaloaf** [comment]
>Calendars are much more complex than a simple seconds/minutes/hours/days.

Very true. I completely forgot I had some table magic going on with the macro to pull my Month and Day. Sorry about that!

>look into SimpleCalendar and see if unsoluble's API can give me a good solution

Do you mean unsoluble's SmallTime or vigoren's Simple Cal? ;-p

Simple Cal has a great API and I remembered that I'm actually already pulling a date from SC so I'll plop (a distilled version of) the code here for you...

```const Year = SimpleCalendar.api.getCurrentYear();
const Month = SimpleCalendar.api.getCurrentMonth();
const Day = SimpleCalendar.api.getCurrentDay();
const Weekday = SimpleCalendar.api.getCurrentWeekday();
ChatMessage.create({    
    content: `Today is ` + Weekday.name + `, ` + Month.name + ` ` + Day.name + `, ` + Year.numericRepresentation
});```

So for my calendar, this displays `Today is Moonsday, Renewfest 1, 1499`

Hope that helps more than confuses!

**Comment by Shuggaloaf** [comment]
@flamewave000 I also just remembered that due to a a request I made over on the Small Time thread, Vigoren (of SimpleCal) got involved and added(/is adding) some ways for other mods to pull info from his. Not sure if this might help you, but here's the link...
https://github.com/unsoluble/smalltime/issues/80

**Comment by flamewave000** [comment]
I know this request has been a VERY long time coming. I really appreciate everyone's patience.

I'm happy to say I've been able to integrate with the SimpleCalendar API and logs can now display the Date and Time according to what is set by that module.
